// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  blog_item: defineAsyncComponent(() => import("./BlogItemSlice/index.vue")),
  hero_slice: defineAsyncComponent(() => import("./HeroSlice/index.vue")),
});
